Repository Nexters/BandalArt-iOS, pull requests merged in 2023-07, with the labels that each got.

#5 update: README.md
  README.md
Labels: feat

#8 chore: Tuist Template 수정 반영
  BandalArt/.gitignore
  BandalArt/.package.resolved
  BandalArt/.tuist-version
  BandalArt/Plugins/UtilPlugin/Plugin.swift
  BandalArt/Plugins/UtilPlugin/ProjectDescriptionHelpers/Dependency+Project.swift
  BandalArt/Plugins/UtilPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  BandalArt/Plugins/UtilPlugin/ProjectDescriptionHelpers/PathExtension.swift
  BandalArt/Plugins/UtilPlugin/ProjectDescriptionHelpers/Project+Templates.swift
  BandalArt/Plugins/UtilPlugin/ProjectDescriptionHelpers/ProjectDeployTarget.swift
  BandalArt/Plugins/UtilPlugin/ProjectDescriptionHelpers/Script.swift
  BandalArt/Projects/App/Project.swift
  BandalArt/Projects/App/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/Contents.json
  BandalArt/Projects/App/Resources/LaunchScreen.storyboard
  BandalArt/Projects/App/Sources/Application/AppDelegate.swift
  BandalArt/Projects/App/Sources/Application/SceneDelegate.swift
  BandalArt/Projects/App/Support/Info.plist
  BandalArt/Projects/App/Tests/.gitkeep
  BandalArt/Projects/Core/Database/Project.swift
  BandalArt/Projects/Core/Database/Sources/Database.swift
  BandalArt/Projects/Core/Database/Tests/DatabaseTests.swift
  BandalArt/Projects/Core/Network/Project.swift
  BandalArt/Projects/Core/Network/Sources/Network.swift
  BandalArt/Projects/Core/Network/Tests/NetworkTests.swift
  BandalArt/Projects/Feature/BottomSheet/Project.swift
  BandalArt/Projects/Feature/BottomSheet/Sources/BottomSheet.swift
  BandalArt/Projects/Feature/BottomSheet/Tests/BottomSheetTests.swift
  BandalArt/Projects/Feature/Common/Project.swift
  BandalArt/Projects/Feature/Common/Sources/Common.swift
  BandalArt/Projects/Feature/Common/Tests/CommonTests.swift
  BandalArt/Projects/Feature/Home/Project.swift
  BandalArt/Projects/Feature/Home/Sources/Home.swift
  BandalArt/Projects/Feature/Home/Tests/HomeTests.swift
  BandalArt/Projects/Feature/Main/Project.swift
  BandalArt/Projects/Feature/Main/Sources/Main.swift
  BandalArt/Projects/Feature/Main/Tests/MainTests.swift
  BandalArt/Projects/Feature/OnBoarding/Project.swift
  BandalArt/Projects/Feature/OnBoarding/Sources/OnBoarding.swift
  BandalArt/Projects/Feature/OnBoarding/Tests/OnBoardingTests.swift
  BandalArt/Projects/Feature/Root/Project.swift
  BandalArt/Projects/Feature/Root/Sources/RootFeature.swift
  BandalArt/Projects/Feature/Root/Tests/RootFeatureTests.swift
  BandalArt/Projects/Feature/Setting/Project.swift
  BandalArt/Projects/Feature/Setting/Sources/Setting.swift
  BandalArt/Projects/Feature/Setting/Tests/SettingTests.swift
  BandalArt/Projects/Shared/Components/Project.swift
  BandalArt/Projects/Shared/Components/Sources/Components.swift
  BandalArt/Projects/Shared/Components/Tests/ComponentsTests.swift
  BandalArt/Projects/Shared/Util/Project.swift
  BandalArt/Projects/Shared/Util/Sources/Util.swift
  BandalArt/Projects/Shared/Util/Tests/UtilTests.swift
  BandalArt/Tuist/Config.swift
  BandalArt/Tuist/Dependencies.swift
  BandalArt/Workspace.swift
Labels: chore, 영민, 상훈

#11 feat: Moya network target 구성
  BandalArt/.gitignore
  BandalArt/Plugins/UtilPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  BandalArt/Projects/Core/Database/Project.swift
  BandalArt/Projects/Core/Network/Project.swift
  BandalArt/Projects/Core/Network/Sources/Infra/APIConstant.swift
  BandalArt/Projects/Core/Network/Sources/Infra/APIEnvironment.swift
  BandalArt/Projects/Core/Network/Sources/Infra/BandalArtTarget+Stub.swift
  BandalArt/Projects/Core/Network/Sources/Infra/BandalArtTarget.swift
  BandalArt/Projects/Core/Network/Sources/Network.swift
  BandalArt/Projects/Core/Network/Sources/Repositorires/BandalArtRepository.swift
  BandalArt/Projects/Core/Network/Sources/Repositorires/BandalArtRepositoryInterface.swift
  BandalArt/Projects/Feature/Common/Tests/CommonTests.swift
  BandalArt/Projects/Feature/OnBoarding/Sources/OnBoarding.swift
  BandalArt/Projects/Shared/Util/Project.swift
  BandalArt/Projects/Shared/Util/Sources/UserDefaultKey.swift
  BandalArt/Projects/Shared/Util/Sources/Util.swift
Labels: feat, P0, 영민, 상훈

#15 feat: emojiview and component 정리
  BandalArt/Projects/Shared/Components/Sources/Components.swift
  BandalArt/Projects/Shared/Components/Sources/Extension/UIColor+Ex.swift
  BandalArt/Projects/Shared/Components/Sources/View/EmojiView.swift
Labels: feat
