Repository Nexters/BandalArt-iOS, pull requests merged in 2023-08, with the labels that each got.

#16 feat: BandalArt Home UI만 구성
  BandalArt/Projects/App/Resources/Assets.xcassets/sub.colorset/Contents.json
  BandalArt/Projects/App/Sources/Application/SceneDelegate.swift
  BandalArt/Projects/Feature/Home/Sources/BandalArtCell.swift
  BandalArt/Projects/Feature/Home/Sources/Home.swift
  BandalArt/Projects/Feature/Home/Sources/HomeViewController.swift
  BandalArt/Projects/Feature/Home/Sources/HomeViewModel.swift
  BandalArt/Projects/Feature/Main/Sources/Main.swift
  BandalArt/Projects/Feature/Main/Sources/MainNavigationController.swift
  BandalArt/Projects/Shared/Components/Sources/AppColor.swift
  BandalArt/Projects/Shared/Components/Sources/Extension/UIColor+Ex.swift
Labels: feat

#20 Feat: BottomSheet UI, Compositional Layout 팩토리, MainGoal 관련 UI 배치
  BandalArt/Projects/App/Resources/Assets.xcassets/chevron.right.imageset/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/chevron.right.imageset/Image.png
  BandalArt/Projects/App/Resources/Assets.xcassets/grass.colorset/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/lemon.colorset/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/purpleblue.colorset/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/purpleblue_sub.colorset/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/sky.colorset/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/yellowred.colorset/Contents.json
  BandalArt/Projects/Feature/BottomSheet/Sources/BottomSheet.swift
  BandalArt/Projects/Feature/Common/.swiftlint.yml
  BandalArt/Projects/Feature/Common/Sources/BaseViewController.swift
  BandalArt/Projects/Feature/Common/Sources/Common.swift
  BandalArt/Projects/Feature/Home/Sources/BottomSheet/Base/BottomSheetController.swift
  BandalArt/Projects/Feature/Home/Sources/BottomSheet/Base/BottomSheetInteractiveDismissalTransition.swift
  BandalArt/Projects/Feature/Home/Sources/BottomSheet/Base/BottomSheetPresentationController.swift
  BandalArt/Projects/Feature/Home/Sources/BottomSheet/Base/BottomSheetTransitioningDelegate.swift
  BandalArt/Projects/Feature/Home/Sources/BottomSheet/Base/Mode.swift
  BandalArt/Projects/Feature/Home/Sources/BottomSheet/Base/SectionLayoutManagerFactory.swift
  BandalArt/Projects/Feature/Home/Sources/BottomSheet/Presentation/Cells/BottomSheetSectionHeader.swift
  BandalArt/Projects/Feature/Home/Sources/BottomSheet/Presentation/Cells/CompletionCell.swift
  BandalArt/Projects/Feature/Home/Sources/BottomSheet/Presentation/Cells/DueDateCell.swift
  BandalArt/Projects/Feature/Home/Sources/BottomSheet/Presentation/Cells/EmojiTitleCell.swift
  BandalArt/Projects/Feature/Home/Sources/BottomSheet/Presentation/Cells/MemoCell.swift
  BandalArt/Projects/Feature/Home/Sources/BottomSheet/Presentation/Cells/ThemeColorCell.swift
  BandalArt/Projects/Feature/Home/Sources/BottomSheet/Presentation/MainGoal/MainGoalView.swift
  BandalArt/Projects/Feature/Home/Sources/BottomSheet/Presentation/MainGoal/MainGoalViewController.swift
  BandalArt/Projects/Feature/Home/Sources/BottomSheet/Presentation/MainGoal/MainGoalViewModel.swift
  BandalArt/Projects/Feature/Home/Sources/BottomSheet/Presentation/MainGoal/MainGoalViewSectionLayoutManager.swift
  BandalArt/Projects/Feature/Home/Sources/BottomSheet/Presentation/SubGoalAndTask/SubGoalAndTaskView.swift
  BandalArt/Projects/Feature/Home/Sources/BottomSheet/Presentation/SubGoalAndTask/SubGoalAndTaskViewController.swift
  BandalArt/Projects/Feature/Home/Sources/BottomSheet/Presentation/SubGoalAndTask/SubGoalAndTaskViewSectionLayoutManager.swift
  BandalArt/Projects/Feature/Home/Sources/HomeViewController.swift
  BandalArt/Projects/Shared/Components/Sources/AppColor.swift
  BandalArt/Projects/Shared/Components/Sources/Extension/UIColor+Ex.swift
  BandalArt/Projects/Shared/Components/Sources/Extension/UIImage+Ex.swift
  BandalArt/Projects/Shared/Components/Sources/View/CircleView.swift
  BandalArt/Projects/Shared/Components/Sources/View/DefaultLabel.swift
  BandalArt/Projects/Shared/Components/Sources/View/DefaultSwitch.swift
  BandalArt/Projects/Shared/Components/Sources/View/SelfSizingCollectionView.swift
  BandalArt/Projects/Shared/Components/Sources/View/UnderlineTextField.swift
  BandalArt/Projects/Shared/Util/Sources/Size.swift
Labels: feat, P0, 상훈

#22 feat: Bottom 모듈 이동 및 지정 접근자 세팅, 린트 추가
  BandalArt/Projects/Core/Database/Sources/Database.swift
  BandalArt/Projects/Core/Database/Tests/DatabaseTests.swift
  BandalArt/Projects/Feature/BottomSheet/.swiftlint.yml
  BandalArt/Projects/Feature/BottomSheet/Sources/Base/BottomSheetController.swift
  BandalArt/Projects/Feature/BottomSheet/Sources/Base/BottomSheetInteractiveDismissalTransition.swift
  BandalArt/Projects/Feature/BottomSheet/Sources/Base/BottomSheetPresentationController.swift
  BandalArt/Projects/Feature/BottomSheet/Sources/Base/BottomSheetTransitioningDelegate.swift
  BandalArt/Projects/Feature/BottomSheet/Sources/Base/Mode.swift
  BandalArt/Projects/Feature/BottomSheet/Sources/Base/SectionLayoutManagerFactory.swift
  BandalArt/Projects/Feature/BottomSheet/Sources/BottomSheet.swift
  BandalArt/Projects/Feature/BottomSheet/Sources/Presentation/Cells/BottomSheetSectionHeader.swift
  BandalArt/Projects/Feature/BottomSheet/Sources/Presentation/Cells/CompletionCell.swift
  BandalArt/Projects/Feature/BottomSheet/Sources/Presentation/Cells/DueDateCell.swift
  BandalArt/Projects/Feature/BottomSheet/Sources/Presentation/Cells/EmojiTitleCell.swift
  BandalArt/Projects/Feature/BottomSheet/Sources/Presentation/Cells/MemoCell.swift
  BandalArt/Projects/Feature/BottomSheet/Sources/Presentation/Cells/ThemeColorCell.swift
  BandalArt/Projects/Feature/BottomSheet/Sources/Presentation/MainGoal/MainGoalView.swift
  BandalArt/Projects/Feature/BottomSheet/Sources/Presentation/MainGoal/MainGoalViewController.swift
  BandalArt/Projects/Feature/BottomSheet/Sources/Presentation/MainGoal/MainGoalViewModel.swift
  BandalArt/Projects/Feature/BottomSheet/Sources/Presentation/MainGoal/MainGoalViewSectionLayoutManager.swift
  BandalArt/Projects/Feature/BottomSheet/Sources/Presentation/SubGoalAndTask/SubGoalAndTaskView.swift
  BandalArt/Projects/Feature/BottomSheet/Sources/Presentation/SubGoalAndTask/SubGoalAndTaskViewController.swift
  BandalArt/Projects/Feature/BottomSheet/Sources/Presentation/SubGoalAndTask/SubGoalAndTaskViewSectionLayoutManager.swift
Labels: fix, P0, 상훈

#23 feat: Home Network Logic (Cell 조회, Detail 조회)
  BandalArt/Projects/App/Resources/Assets.xcassets/Gray/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/Gray/gray100.colorset/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/Gray/gray200.colorset/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/Gray/gray300.colorset/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/Gray/gray400.colorset/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/Gray/gray50.colorset/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/Gray/gray500.colorset/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/Gray/gray600.colorset/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/Gray/gray700.colorset/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/Gray/gray800.colorset/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/Gray/gray900.colorset/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/Sub/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/Sub/darkNavy.colorset/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/Sub/lightGrape.colorset/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/Theme/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/Theme/grape.colorset/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/Theme/grass.colorset/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/Theme/lemon.colorset/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/Theme/mandarin.colorset/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/Theme/mint.colorset/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/Theme/sky.colorset/Contents.json
  BandalArt/Projects/App/Sources/Application/SceneDelegate.swift
  BandalArt/Projects/Core/Network/Sources/DataMapping/BandalArtCellInfoResponseDTO.swift
  BandalArt/Projects/Core/Network/Sources/DataMapping/BandalArtDetailResponseDTO.swift
  BandalArt/Projects/Core/Network/Sources/Infra/APIConstant.swift
  BandalArt/Projects/Core/Network/Sources/Infra/BandalArtTarget.swift
  BandalArt/Projects/Core/Network/Sources/Repositorires/BandalArtRepository.swift
  BandalArt/Projects/Core/Network/Sources/Repositorires/BandalArtRepositoryImpl.swift
  BandalArt/Projects/Core/Network/Sources/Repositorires/BandalArtRepositoryInterface.swift
  BandalArt/Projects/Domain/Entity/Sources/BandalArtCellInfo.swift
  BandalArt/Projects/Domain/Entity/Sources/BandalArtInfo.swift
  BandalArt/Projects/Domain/Entity/Sources/Entity.swift
  BandalArt/Projects/Domain/Interface/Sources/BandalArtRepo+Error.swift
  BandalArt/Projects/Domain/Interface/Sources/Protocols.swift
  BandalArt/Projects/Domain/UseCase/Sources/BandalArtUseCase.swift
  BandalArt/Projects/Domain/UseCase/Sources/UseCase.swift
  BandalArt/Projects/Feature/BottomSheet/Sources/Presentation/MainGoal/MainGoalViewController.swift
  BandalArt/Projects/Feature/Home/Sources/BandalArtCell.swift
  BandalArt/Projects/Feature/Home/Sources/HomeViewController.swift
  BandalArt/Projects/Feature/Home/Sources/HomeViewModel.swift
  BandalArt/Projects/Shared/Components/Sources/AppColorCase.swift
  BandalArt/Projects/Shared/Components/Sources/Extension/UIColor+Ex.swift
  BandalArt/Projects/Shared/Components/Sources/View/EmojiView.swift
  BandalArt/Projects/Shared/Util/Sources/Collection+Ex.swift
Labels: P0, 영민

#29 feat: Application Asset , Font 정리
  BandalArt/Projects/App/Resources/Assets.xcassets/chevron.down.imageset/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/chevron.down.imageset/chevron.down.png
  BandalArt/Projects/App/Resources/Assets.xcassets/chevron.right.imageset/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/chevron.right.imageset/chevron.right.png
  BandalArt/Projects/App/Resources/Assets.xcassets/chevron.right.imageset/chevron.right@2x.png
  BandalArt/Projects/App/Resources/Assets.xcassets/chevron.right.imageset/chevron.right@3x.png
  BandalArt/Projects/App/Resources/Assets.xcassets/xmark.imageset/Contents.json
  BandalArt/Projects/App/Resources/Assets.xcassets/xmark.imageset/xmark.png
  BandalArt/Projects/App/Resources/Assets.xcassets/xmark.imageset/xmark@2x.png
  BandalArt/Projects/App/Resources/Assets.xcassets/xmark.imageset/xmark@3x.png
  BandalArt/Projects/App/Resources/Pretendard-Bold.otf
  BandalArt/Projects/App/Resources/Pretendard-Medium.otf
  BandalArt/Projects/App/Resources/Pretendard-Regular.otf
  BandalArt/Projects/App/Resources/neurimboGothicRegular.otf
  BandalArt/Projects/App/Support/Info.plist
  BandalArt/Projects/Feature/Home/Sources/BandalArtCell.swift
  BandalArt/Projects/Feature/Home/Sources/HomeViewController.swift
  BandalArt/Projects/Feature/Setting/Sources/Setting.swift
  BandalArt/Projects/Feature/Setting/Tests/SettingTests.swift
  BandalArt/Projects/Shared/Components/Sources/Extension/UIFont+Ex.swift
Labels: chore
